name: Send AI Digest

on:
  schedule:
    - cron: '45 11 * * *'  # 13:45 Uhr MEZ (GitHub verwendet UTC)
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests beautifulsoup4 feedparser

    - name: Run script
      run: python daily_digest.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
